// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViixsDockerManager.DockLight.Environments;

#nullable disable

namespace ViixsDockerManager.DockLight.Environments.Migrations
{
    [DbContext(typeof(DocklightEnvironmentReadDbContext))]
    [Migration("20250902000641_UpdateWindowsLocation")]
    partial class UpdateWindowsLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ViixsDockerManager.DockLight.Shared.Entities.DocklightEnvironment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("EnvironmentId");

                    b.ToTable("DocklightEnvironment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApiLocation = "/var/run/docker.sock",
                            EnvironmentId = new Guid("34805c86-9086-45e1-b264-241983acc044"),
                            Name = "Local"
                        },
                        new
                        {
                            Id = 2,
                            ApiLocation = "/pipe/docker_engine",
                            EnvironmentId = new Guid("65670bc8-fb6e-413a-9492-3ba24fd4f8ff"),
                            Name = "LocalWindows"
                        },
                        new
                        {
                            Id = 3,
                            ApiLocation = "http://nas",
                            EnvironmentId = new Guid("1acf8e3c-495a-4258-a280-cc7acf504c0e"),
                            Name = "Nas"
                        },
                        new
                        {
                            Id = 4,
                            ApiLocation = "http://nuc",
                            EnvironmentId = new Guid("4d9e6256-d601-41f4-abe6-a42f40100008"),
                            Name = "Nuc"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
