// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViixsDockerManager.DockLight.Environments.DbContexts;

#nullable disable

namespace ViixsDockerManager.DockLight.Environments.Migrations
{
    [DbContext(typeof(DockLightEnvironmentWriteDbContext))]
    partial class DockLightEnvironmentWriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ViixsDockerManager.DockLight.Shared.Entities.DockLightEnvironment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("EnvironmentId");

                    b.ToTable("DockLightEnvironments");
                });
#pragma warning restore 612, 618
        }
    }
}
