// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViixsDockerManager.DockLight.Environments;

#nullable disable

namespace ViixsDockerManager.DockLight.Environments.Migrations
{
    [DbContext(typeof(DocklightEnvironmentReadDbContext))]
    partial class DocklightEnvironmentReadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ViixsDockerManager.DockLight.Environments.Entities.DocklightEnvironment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DocklightEnvironment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApiLocation = "/var/docker/docker.sock",
                            Name = "Local"
                        },
                        new
                        {
                            Id = 2,
                            ApiLocation = "http://nas",
                            Name = "Nas"
                        },
                        new
                        {
                            Id = 3,
                            ApiLocation = "http://nuc",
                            Name = "Nuc"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
