<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>214c193f-37ec-4218-bf3c-06005ce2573f</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <PropertyGroup Label="Docker">        
        <DockerFileRunArguments Condition="'$(Configuration)'=='Debug'">-v $(USERPROFILE)/ViixsDockerManager/InDocker:/app/data -v //var/run/docker.sock:/var/run/docker.sock:z</DockerFileRunArguments>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.9" />
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
        <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
        <PackageReference Include="Serilog.Sinks.OpenTelemetry" Version="4.2.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\viixsdockermanager.client\viixsdockermanager.client.esproj">
            <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
        </ProjectReference>
        <ProjectReference Include="..\ViixsDockerManager.DockLight.Environments\ViixsDockerManager.DockLight.Environments.csproj" />
        <ProjectReference Include="..\ViixsDockerManager.DockLight.Containers\ViixsDockerManager.DockLight.Containers.csproj" />
        <ProjectReference Include="..\ViixsDockerManager.ServiceDefaults\ViixsDockerManager.ServiceDefaults.csproj" />
        <ProjectReference Include="..\ViixsDockerManager.Shared.Database.Sqlite\ViixsDockerManager.Shared.Database.Sqlite.csproj" />
        <ProjectReference Include="..\ViixsDockerManager.Shared\ViixsDockerManager.Shared.csproj" />
        <ProjectReference Include="..\ViixsDockerManager.AspNet.Shared\ViixsDockerManager.Shared.AspNet.csproj" />
        <ProjectReference Include="..\ViixsDockerManager.Users.Accounts\ViixsDockerManager.Users.Accounts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\" />
    </ItemGroup>

</Project>
