<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>        
        <PackageReference Include="Docker.DotNet.Enhanced" Version="3.128.5" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\ViixDockerManager.AspNet.Shared\ViixDockerManager.AspNet.Shared.csproj" />
        <ProjectReference Include="..\ViixsDockerManager.Shared\ViixsDockerManager.Shared.csproj" />
    </ItemGroup>

</Project>
