using System.Text;
using ViixsDockerManager.Shared.SourceGenerators.Builders.Interfaces;

using static ViixsDockerManager.Shared.SourceGenerators.Constants.ClassSymbolsConstants;

namespace ViixsDockerManager.Shared.SourceGenerators.Builders.Models;

internal class Classz : IClass
{
    public string? ClassName { get; set; }
    public INameSpace? NameSpace { get; set; }
    public ICollection<IUsing>? Usings { get; }
    public ICollection<Modifier>? Modifiers { get; }
    public ICollection<IMethod>? Methods { get; }

    public Classz()
    {
        Usings = [];
        Modifiers = [];
        Methods = [];
    }

    public string GetClassString()
    {
        var stringBuilder = new StringBuilder();
        stringBuilder.AppendLine("// <auto-generated />");
        stringBuilder.AppendLine("#nullable enable");
        foreach (var usingString in Usings!)
        {
            stringBuilder.AppendLine(usingString.GetUsingString());
        }
        if (Usings.Any())
        {
            stringBuilder.AppendLine();
        }
        if (NameSpace != null)
        {
            stringBuilder.AppendLine(NameSpace.GetNameSpaceString());
            stringBuilder.AppendLine();
        }

        var modifiersString = string.Join(" ", Modifiers.OrderBy(m => m.Order).Select(modifier => (string)modifier));
        stringBuilder.AppendLine($"{modifiersString} class {ClassName}");
        stringBuilder.AppendLine(OpenBrace);
        foreach (var method in Methods!)
        {
            var methodString = method.GetMethodString(Indentation.Indent4);
            stringBuilder.AppendLine(methodString);
        }
        stringBuilder.AppendLine(CloseBrace);
        return stringBuilder.ToString();
    }
}
