using System.Diagnostics.CodeAnalysis;

namespace ViixsDockerManager.Shared.SourceGenerators.Constants;

internal static class ViixsControllerAttributeDefinition
{
    
    public const string FileName = "ViixsControllerAttribute.g.cs";
    public const string FullTypeName = "ViixsDockerManager.Shared.Attributes.ViixsControllerAttribute";
    //TODO: Move to file and read from there. Or embed as resource.
    public const string ViixControllerAttributeText = """
        // <auto-generated/>
        #nullable enable
        using System;
        using Microsoft.CodeAnalysis;
        
        namespace ViixsDockerManager.Shared.Attributes
        {        
            [Embedded]
            [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
            public class ViixsControllerAttribute : Attribute           
            {
                public ViixsControllerAttribute(Type? queryOrCommandType = null)
                {      
                    QueryOrCommandTypeName = queryOrCommandType?.Name ?? string.Empty;
                }

                public string QueryOrCommandTypeName { get; }
                public string ControllerName { get; init; } = string.Empty;
                public string Action { get; init; } = string.Empty;
                public string HttpMethod { get; init; } = "GET";
            }
        }
        """;
}
