<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DockerManager.Auth\DockerManager.Auth.csproj" />
      <ProjectReference Include="..\DockerManager.DockerControl\DockerManager.DockerControl.csproj" />
      <ProjectReference Include="..\DockerManager.Shared.Views\DockerManager.Shared.Views.csproj" />
      <ProjectReference Include="..\DockerManager.Shared\DockerManager.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.13.1" />
      <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.9.2">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Components\Pages\Account\" />
    </ItemGroup>
    
    <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
        <Exec Command="npm run build:css" />
    </Target>

</Project>
